run:
  issues-exit-code: 1
  tests: true
output:
  format: colored-line-number
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  funlen:
    lines: 90
    statements: 50
  gocognit:
    min-complexity: 10
  nestif:
    min-complexity: 4
  gocritic:
    enabled-tags:
      - performance
    disabled-tags:
      - experimental
    settings:
      captLocal:
        paramsOnly: true
  gofmt:
    simplify: true
  revive:
    confidence: 0.8
  govet:
    check-shadowing: false
    enable:
      - atomicalign
    enable-all: false
    disable:
      - shadow
    disable-all: false
linters:
  enable:
    - funlen
    - govet
    - gofmt
    - gocritic
    - misspell
    - revive
  disable:
    - scopelint
  presets:
    - bugs
    - unused
  fast: false
