package polling

import (
	"github.com/zemlyak-l/vkgottle/object"
)

type Routes struct {
	MessageNew                    func(object.NewMessage)
	MessageReply                  func(object.NewMessage)
	MessageEdit                   func(object.NewMessage)
	MessageAllow                  func(object.MessageAllowObject)
	MessageDeny                   func(object.MessageDenyObject)
	MessageTypingState            func(object.MessageTypingStateObject)
	MessageEvent                  func(object.MessageEventObject)
	PhotoNew                      func(object.Photo)
	PhotoCommentNew               func(interface{})
	PhotoCommentEdit              func(interface{})
	PhotoCommentRestore           func(interface{})
	PhotoCommentDelete            func(interface{})
	AudioNew                      func(interface{})
	VideoNew                      func(interface{})
	VideoCommentNew               func(interface{})
	VideoCommentEdit              func(interface{})
	VideoCommentRestore           func(interface{})
	VideoCommentDelete            func(object.VideoCommentDeleteObject)
	WallPostNew                   func(interface{})
	WallRepost                    func(interface{})
	WallReplyNew                  func(interface{})
	WallReplyEdit                 func(interface{})
	WallReplyRestore              func(interface{})
	WallReplyDelete               func(object.WallReplyDeleteObject)
	BoardPostNew                  func(interface{})
	BoardPostEdit                 func(interface{})
	BoardPostRestore              func(interface{})
	BoardPostDelete               func(object.BoardPostDeleteObject)
	MarketCommentNew              func(interface{})
	MarketCommentEdit             func(interface{})
	MarketCommentRestore          func(interface{})
	MarketCommentDelete           func(object.MarketCommentDeleteObject)
	MarketOrderNew                func(interface{})
	MarketOrderEdit               func(interface{})
	GroupLeave                    func(object.GroupLeaveObject)
	GroupJoin                     func(object.GroupJoinObject)
	UserBlock                     func(object.UserBlockObject)
	UserUnblock                   func(object.UserUnblockObject)
	PollVoteNew                   func(object.PollVoteNewObject)
	GroupOfficersEdit             func(object.GroupOfficersEditObject)
	GroupChangeSettings           func(object.GroupChangeSettingsObject)
	GroupChangePhoto              func(object.GroupChangePhotoObject)
	VkpayTransaction              func(object.VkpayTransactionObject)
	LeadFormsNew                  func(object.LeadFormsNewObject)
	AppPayload                    func(object.AppPayloadObject)
	MessageRead                   func(object.MessageReadObject)
	LikeAdd                       func(object.LikeAddObject)
	LikeRemove                    func(object.LikeRemoveObject)
	DonutSubscriptionCreate       func(object.DonutSubscriptionCreateObject)
	DonutSubscriptionProlonged    func(object.DonutSubscriptionProlongedObject)
	DonutSubscriptionExpired      func(object.DonutSubscriptionExpiredObject)
	DonutSubscriptionCancelled    func(object.DonutSubscriptionCancelledObject)
	DonutSubscriptionPriceChanged func(object.DonutSubscriptionPriceChangedObject)
	DonutMoneyWithdraw            func(object.DonutMoneyWithdrawObject)
	DonutMoneyWithdrawError       func(object.DonutMoneyWithdrawErrorObject)
}
